### ISSUE TITLE
Decide upon the choice of wifi receivers to be used. 

### ISSUE THREAD

**Issue by pranav1001** [pranav1001/Position-Me-Baby#2]
I guess we have two straightforward options: 
- Our cellphones. 
- Zigbee (an IEEE 802 device used in communications)
If there are other viable options, you can definitely suggest them :smiley:

**Comment by saqib1707** [comment]
I dont think personally using an app(mobile) as an object would be good since it won't be a feasible solution to our problem. The tracking device should be some simple hardware (zigbee would work except for the cost)
